version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis_jobs:
    image: redis:latest
    container_name: nest_redis_jobs
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_jobs_data:/data
  redis_cache:
    image: redis:latest
    container_name: nest_redis_cache
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_cache_data:/data

volumes:
  postgres_data:
  redis_jobs_data:
  redis_cache_data:
